server:
  port: 0

spring:
  application:
    name: users-ws

  devtools:
    restart:
      enable: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:tesetdb

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
  ip: 59.29.224.144

token:
  expiration_time: 864000000
  secret: local_secret

